### PR TITLE
Add modulename to console.js write for parity with graylog's 'facility'

### PR DESCRIPTION
**Pull request by robert-chiniquy**
It will be sweet to distinguish log messages in the browser by which module they're from.

### CODE REVIEW

**Comment by pquerna** [comment]
i kinda think this should be a k/v, not really pre-pended to the message, mostly because the length of the string for the module name varies between modules.

**Comment by pquerna** [comment]
so this also relates to the length of the LEVEL STRING -- which I would also like to change to be a static length for the console output.

**Comment by robert-chiniquy** [comment]
fixt

**Comment by robert-chiniquy** [comment]
thx

**Pull request merged**
